import pptxgen from 'pptxgenjs';
import jsPDF from 'jspdf';
import { PresentationData, MCQQuizData, MindMapData } from '../types/studyMaterial';

export class ExportService {
  /**
   * Export Presentation to a real .pptx PowerPoint file
   */
  public static async exportToPPTX(presentation: PresentationData, fileName?: string): Promise<void> {
    const pptx = new pptxgen();
    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'AI Whiteboard — Built by SAFA Developers';
    pptx.company = 'AI Whiteboard';
    pptx.title = presentation.title;

    // Slide theme colors
    const primaryColor = '3730A3'; // Indigo 800
    const textColor = '1E293B'; // Slate 800
    const lightBg = 'F8FAFC'; // Slate 50

    presentation.slides.forEach((slideData) => {
      const slide = pptx.addSlide();
      slide.background = { color: lightBg };

      if (slideData.layout === 'title') {
        // Title Slide Layout
        slide.addText(slideData.title, {
          x: 0.8,
          y: 2.0,
          w: '85%',
          h: 1.8,
          fontSize: 38,
          bold: true,
          color: primaryColor,
          fontFace: 'Arial',
        });

        if (slideData.subtitle) {
          slide.addText(slideData.subtitle, {
            x: 0.8,
            y: 3.8,
            w: '85%',
            h: 1.0,
            fontSize: 20,
            color: '64748B',
            fontFace: 'Arial',
          });
        }

        slide.addText('Generated by AI Whiteboard • Built by SAFA Developers', {
          x: 0.8,
          y: 6.2,
          w: '85%',
          fontSize: 12,
          color: '94A3B8',
          italic: true,
        });
      } else if (slideData.layout === 'split') {
        // Two-Column Split Layout
        slide.addText(slideData.title, {
          x: 0.8,
          y: 0.6,
          w: '85%',
          h: 0.8,
          fontSize: 26,
          bold: true,
          color: primaryColor,
        });

        // Left Box
        if (slideData.leftPoints && slideData.leftPoints.length > 0) {
          slide.addShape(pptx.ShapeType.rect, {
            x: 0.8,
            y: 1.6,
            w: 5.6,
            h: 4.8,
            fill: { color: 'FFFFFF' },
            line: { color: 'E2E8F0', width: 1 },
          });

          slide.addText(slideData.leftPoints.join('\n\n'), {
            x: 1.0,
            y: 1.8,
            w: 5.2,
            h: 4.4,
            fontSize: 14,
            color: textColor,
            valign: 'top',
          });
        }

        // Right Box
        if (slideData.rightPoints && slideData.rightPoints.length > 0) {
          slide.addShape(pptx.ShapeType.rect, {
            x: 6.8,
            y: 1.6,
            w: 5.6,
            h: 4.8,
            fill: { color: 'FFFFFF' },
            line: { color: 'E2E8F0', width: 1 },
          });

          slide.addText(slideData.rightPoints.join('\n\n'), {
            x: 7.0,
            y: 1.8,
            w: 5.2,
            h: 4.4,
            fontSize: 14,
            color: textColor,
            valign: 'top',
          });
        }
      } else {
        // Default / Bullet Points / Diagram Layout
        slide.addText(slideData.title, {
          x: 0.8,
          y: 0.6,
          w: '85%',
          h: 0.8,
          fontSize: 26,
          bold: true,
          color: primaryColor,
        });

        const points = slideData.bulletPoints || [];
        if (points.length > 0) {
          slide.addText(
            points.map((p) => ({ text: p, options: { bullet: true, breakLine: true } })),
            {
              x: 0.8,
              y: 1.6,
              w: '85%',
              h: 4.5,
              fontSize: 16,
              color: textColor,
              lineSpacing: 28,
              valign: 'top',
            }
          );
        }
      }

      // Add Footer
      slide.addText(`AI Whiteboard — ${presentation.title}`, {
        x: 0.8,
        y: 6.8,
        w: 6.0,
        fontSize: 9,
        color: '94A3B8',
      });

      slide.addText(`Slide ${slideData.slideNumber} • Built by SAFA Developers`, {
        x: 8.0,
        y: 6.8,
        w: 4.5,
        fontSize: 9,
        color: '94A3B8',
        align: 'right',
      });
    });

    const safeName = (fileName || presentation.title || 'study_presentation').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    await pptx.writeFile({ fileName: `${safeName}.pptx` });
  }

  /**
   * Export Presentation Deck to a formatted PDF file
   */
  public static exportPresentationToPDF(presentation: PresentationData, fileName?: string): void {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    presentation.slides.forEach((slide, idx) => {
      if (idx > 0) doc.addPage();

      // Background
      doc.setFillColor(248, 250, 252); // Slate 50
      doc.rect(0, 0, pageWidth, pageHeight, 'F');

      // Top Accent Line
      doc.setFillColor(79, 70, 229); // Indigo 600
      doc.rect(0, 0, pageWidth, 5, 'F');

      // Slide Title
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(55, 48, 163); // Indigo 800
      doc.text(slide.title, margin, 25);

      if (slide.subtitle) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(14);
        doc.setTextColor(100, 116, 139); // Slate 500
        doc.text(slide.subtitle, margin, 35);
      }

      // Slide Body Content
      let yPos = slide.subtitle ? 50 : 40;

      if (slide.layout === 'split') {
        // Left Column (Advantages)
        if (slide.leftPoints && slide.leftPoints.length > 0) {
          doc.setFillColor(255, 255, 255);
          doc.roundedRect(margin, yPos, 120, 120, 3, 3, 'F');

          let leftY = yPos + 10;
          doc.setFontSize(11);
          doc.setTextColor(30, 41, 59);
          slide.leftPoints.forEach((pt) => {
            const splitPt = doc.splitTextToSize(pt, 110);
            doc.text(splitPt, margin + 5, leftY);
            leftY += splitPt.length * 6 + 4;
          });
        }

        // Right Column (Disadvantages)
        if (slide.rightPoints && slide.rightPoints.length > 0) {
          doc.setFillColor(255, 255, 255);
          doc.roundedRect(150, yPos, 120, 120, 3, 3, 'F');

          let rightY = yPos + 10;
          doc.setFontSize(11);
          doc.setTextColor(30, 41, 59);
          slide.rightPoints.forEach((pt) => {
            const splitPt = doc.splitTextToSize(pt, 110);
            doc.text(splitPt, 155, rightY);
            rightY += splitPt.length * 6 + 4;
          });
        }
      } else {
        // Bullets / Diagram Layout
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(margin, yPos, pageWidth - margin * 2, 125, 4, 4, 'F');

        let contentY = yPos + 12;

        if (slide.diagramDescription) {
          doc.setFont('courier', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(79, 70, 229);
          const diagLines = doc.splitTextToSize(`[ Diagram Flow ]\n${slide.diagramDescription}`, 240);
          doc.text(diagLines, margin + 8, contentY);
          contentY += diagLines.length * 5 + 6;
        }

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.setTextColor(30, 41, 59);

        const points = slide.bulletPoints || [];
        points.forEach((pt) => {
          const splitPt = doc.splitTextToSize(`•  ${pt}`, 240);
          doc.text(splitPt, margin + 8, contentY);
          contentY += splitPt.length * 7 + 3;
        });
      }

      // Footer
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184); // Slate 400
      doc.text(`AI Whiteboard — ${presentation.title}`, margin, pageHeight - 12);
      doc.text(`Slide ${slide.slideNumber} of ${presentation.slides.length} • Built by SAFA Developers`, pageWidth - margin - 80, pageHeight - 12);
    });

    const safeName = (fileName || presentation.title || 'presentation').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`${safeName}.pdf`);
  }

  /**
   * Export MCQ Quiz to formatted Printable PDF
   */
  public static exportQuizToPDF(quiz: MCQQuizData): void {
    const doc = new jsPDF();
    const margin = 20;
    let y = margin;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(79, 70, 229);
    doc.text(quiz.title, margin, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated on: ${new Date().toLocaleDateString()} | Topic: ${quiz.topic}`, margin, y);
    y += 5;
    doc.text('AI Whiteboard — Built by SAFA Developers', margin, y);
    y += 15;

    // Questions
    quiz.questions.forEach((q, idx) => {
      if (y > 250) {
        doc.addPage();
        y = margin;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(30, 41, 59);
      const qText = `${idx + 1}. ${q.question} [${q.difficulty.toUpperCase()}]`;
      const splitQ = doc.splitTextToSize(qText, 170);
      doc.text(splitQ, margin, y);
      y += splitQ.length * 6 + 4;

      // Options
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      q.options.forEach((opt, optIdx) => {
        const letters = ['A', 'B', 'C', 'D'];
        doc.setTextColor(71, 85, 105);
        doc.text(`    (${letters[optIdx]}) ${opt}`, margin, y);
        y += 6;
      });

      // Answer & Explanation
      y += 2;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(16, 185, 129);
      const letters = ['A', 'B', 'C', 'D'];
      doc.text(`    Correct Answer: (${letters[q.correctAnswerIndex]})`, margin, y);
      y += 5;

      doc.setTextColor(100, 116, 139);
      const expSplit = doc.splitTextToSize(`    Rationale: ${q.explanation}`, 160);
      doc.text(expSplit, margin, y);
      y += expSplit.length * 5 + 10;
    });

    const safeName = (quiz.title || 'quiz').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`${safeName}.pdf`);
  }

  /**
   * Export study notes & slides as formatted Microsoft Word document (.doc / .docx)
   */
  public static exportToWordDoc(packageData: { topic: string; summary: string; presentation?: any; quiz?: any; extractedKeywords?: string[] }, fileName?: string): void {
    const title = packageData.topic || 'Study Notes';
    let contentHtml = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${title}</title>
        <style>
          body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 11pt; color: #1e293b; line-height: 1.6; }
          h1 { font-size: 24pt; color: #3730a3; border-bottom: 2pt solid #4f46e5; padding-bottom: 6pt; }
          h2 { font-size: 16pt; color: #4338ca; margin-top: 18pt; border-bottom: 1pt solid #cbd5e1; }
          h3 { font-size: 13pt; color: #1e293b; margin-top: 12pt; }
          .summary-box { background: #f8fafc; border-left: 4pt solid #4f46e5; padding: 12pt; margin: 12pt 0; font-size: 11pt; }
          .slide-card { background: #ffffff; border: 1pt solid #e2e8f0; padding: 12pt; margin-bottom: 12pt; border-radius: 6pt; }
          .mcq-box { background: #f0fdf4; border: 1pt solid #bbf7d0; padding: 10pt; margin-bottom: 10pt; border-radius: 4pt; }
          .badge { display: inline-block; background: #e0e7ff; color: #3730a3; padding: 3pt 8pt; border-radius: 4pt; font-size: 9pt; font-weight: bold; margin-right: 4pt; }
          .footer { font-size: 9pt; color: #94a3b8; margin-top: 30pt; border-top: 1pt solid #e2e8f0; padding-top: 8pt; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p><strong>Generated by:</strong> AI Whiteboard (Built by SAFA Developers) • <strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        
        <div class="summary-box">
          <strong>Executive Topic Summary:</strong><br/>
          ${packageData.summary}
        </div>

        ${packageData.extractedKeywords ? `
          <p><strong>Key Concept Tags:</strong><br/>
            ${packageData.extractedKeywords.map(k => `<span class="badge">#${k}</span>`).join(' ')}
          </p>
        ` : ''}

        ${packageData.presentation ? `
          <h2>Structured Lecture Slides Breakdown</h2>
          ${packageData.presentation.slides.map((s: any, idx: number) => `
            <div class="slide-card">
              <h3>Slide ${idx + 1}: ${s.title}</h3>
              ${s.subtitle ? `<p><em>${s.subtitle}</em></p>` : ''}
              ${s.bullets ? `<ul>${s.bullets.map((b: string) => `<li>${b}</li>`).join('')}</ul>` : ''}
              ${s.notes ? `<p style="color: #64748b; font-size: 10pt;"><strong>Presenter Notes:</strong> ${s.notes}</p>` : ''}
            </div>
          `).join('')}
        ` : ''}

        ${packageData.quiz ? `
          <h2>High-Yield Practice Questions & Answers</h2>
          ${packageData.quiz.questions.map((q: any, idx: number) => `
            <div class="mcq-box">
              <p><strong>Q${idx + 1}: ${q.question}</strong> <em>[${(q.difficulty || 'Medium').toUpperCase()}]</em></p>
              <ul>
                ${q.options.map((opt: string, optI: number) => `<li>(${['A','B','C','D'][optI]}) ${opt}</li>`).join('')}
              </ul>
              <p style="color: #059669; font-weight: bold;">✓ Correct Answer: (${['A','B','C','D'][q.correctAnswerIndex]}) ${q.options[q.correctAnswerIndex]}</p>
              <p style="color: #475569; font-size: 10pt;"><strong>Explanation:</strong> ${q.explanation}</p>
            </div>
          `).join('')}
        ` : ''}

        <div class="footer">
          Document synthesized via AI Multimodal Whiteboard • Built by SAFA Developers
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', contentHtml], {
      type: 'application/msword;charset=utf-8'
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const safeName = (fileName || title).replace(/[^a-z0-9]/gi, '_').toLowerCase();
    a.download = `${safeName}_study_guide.doc`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export Markdown Document (.md)
   */
  public static exportToMarkdownDoc(packageData: { topic: string; summary: string; presentation?: any; quiz?: any }, fileName?: string): void {
    let md = `# ${packageData.topic || 'Study Notes'}\n\n`;
    md += `> Generated by AI Whiteboard (Built by SAFA Developers) on ${new Date().toLocaleDateString()}\n\n`;
    md += `## Executive Summary\n${packageData.summary}\n\n`;

    if (packageData.presentation) {
      md += `## Lecture Slides\n\n`;
      packageData.presentation.slides.forEach((s: any, idx: number) => {
        md += `### Slide ${idx + 1}: ${s.title}\n`;
        if (s.subtitle) md += `*${s.subtitle}*\n\n`;
        if (s.bullets) s.bullets.forEach((b: string) => { md += `- ${b}\n`; });
        if (s.notes) md += `\n> **Notes:** ${s.notes}\n`;
        md += `\n---\n\n`;
      });
    }

    if (packageData.quiz) {
      md += `## MCQ Practice Quiz\n\n`;
      packageData.quiz.questions.forEach((q: any, idx: number) => {
        md += `**Q${idx + 1}. ${q.question}** [${q.difficulty.toUpperCase()}]\n`;
        const letters = ['A', 'B', 'C', 'D'];
        q.options.forEach((opt: string, optI: number) => {
          md += `- (${letters[optI]}) ${opt}\n`;
        });
        md += `\n**Correct Answer:** (${letters[q.correctAnswerIndex]}) ${q.options[q.correctAnswerIndex]}\n`;
        md += `*Rationale:* ${q.explanation}\n\n`;
      });
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const safeName = (fileName || packageData.topic || 'notes').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    a.download = `${safeName}_notes.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export JSON data
   */
  public static exportToJSON(data: any, fileName: string): void {
    const jsonStr = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Export canvas image snapshot as PNG
   */
  public static downloadCanvasImage(dataUrl: string, fileName: string): void {
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = `${fileName}.png`;
    a.click();
  }
}
